language: go

cache:
  directories:
    - $GOPATH/pkg/mod

env:
  - GO111MODULE=on

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

before_install:
  - go get github.com/onsi/gomega github.com/onsi/ginkgo/ginkgo
  - go mod download
  - go mod verify

script:
  - ginkgo -r -race -coverprofile=coverage.txt -covermode=atomic

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

after_success:
  - bash <(curl -s https://codecov.io/bash)
