// Code generated by sts v0.0.3-alpha-dev. DO NOT EDIT.

package examples

func subsrc2anysub(src subsrc) anysub {
	return anysub{
		Test: src.Field1,
	}
}
func anysub2subsrc(src anysub) subsrc {
	return subsrc{
		Field1: src.Test,
	}
}
func subsrcPtr2anysubPtr(src *subsrc) *anysub {
	if src == nil {
		return nil
	}
	m := subsrc2anysub(*src)
	return &m
}
func anysubPtr2subsrcPtr(src *anysub) *subsrc {
	if src == nil {
		return nil
	}
	m := anysub2subsrc(*src)
	return &m
}
