// Code generated by sts v0.0.3-alpha-dev. DO NOT EDIT.

package output

import (
	"github.com/ekhabarov/sts/examples"
	"github.com/ekhabarov/sts/examples/dest"
)

func Source2Dest(src examples.Source) dest.Dest {
	return dest.Dest{
		I64:       int64(src.I1),
		B:         Int2Bool(src.I2),
		Nt:        TimeTimePtr2NullsTime(src.PT),
		JsonField: src.JJ,
		DB:        int64(src.D),
	}
}
func Dest2Source(src dest.Dest) examples.Source {
	return examples.Source{
		I1: int(src.I64),
		I2: Bool2Int(src.B),
		PT: NullsTime2TimeTimePtr(src.Nt),
		JJ: src.JsonField,
		D:  int32(src.DB),
	}
}
func SourcePtr2DestPtr(src *examples.Source) *dest.Dest {
	if src == nil {
		return nil
	}
	m := Source2Dest(*src)
	return &m
}
func DestPtr2SourcePtr(src *dest.Dest) *examples.Source {
	if src == nil {
		return nil
	}
	m := Dest2Source(*src)
	return &m
}
