// Auto-generated code. DO NOT EDIT!!!
// Generated by sts v0.0.2-alpha-dev.

package output

import (
	"github.com/ekhabarov/sts/examples"
	"github.com/ekhabarov/sts/examples/dest"
)

func Source2Dest(src examples.Source) dest.Dest {
	return dest.Dest{
		I64:       int64(src.I1),
		B:         Int2Bool(src.I2),
		Nt:        TimeTimePtr2NullsTime(src.PT),
		JsonField: src.JJ,
		DB:        int64(src.D),
	}
}
func Dest2Source(src dest.Dest) examples.Source {
	return examples.Source{
		I1: int(src.I64),
		I2: Bool2Int(src.B),
		PT: NullsTime2TimeTimePtr(src.Nt),
		JJ: src.JsonField,
		D:  int32(src.DB),
	}
}
